import type { Category, Product } from '@/types';

export const categories: Category[] = [
  {
    slug: 'seragam-sekolah',
    name: 'Seragam Sekolah',
    description:
      'Seragam siswa dan siswi dengan bahan nyaman, tahan lama, dan sesuai standar sekolah.',
    image:
      '/images/categories/seragam-sekolah.jpg',
    icon: 'GraduationCap',
    productCount: 13,
  },
  {
    slug: 'seragam-perusahaan',
    name: 'Seragam Perusahaan',
    description:
      'Seragam kerja profesional yang merepresentasikan identitas brand perusahaan Anda.',
    image:
      '/images/categories/seragam-perusahaan.jpg',
    icon: 'Building2',
    productCount: 9,
  },
  {
    slug: 'kaos-custom',
    name: 'Kaos Custom',
    description:
      'Kaos sablon custom dengan teknik sablon premium dan bahan katun combed berkualitas.',
    image:
      '/images/categories/kaos-custom.jpg',
    icon: 'Shirt',
    productCount: 15,
  },
  {
    slug: 'fashion-stylish',
    name: 'Fashion Stylish',
    description:
      'Busana muslim modern dan pakaian stylish dengan desain kekinian dan bahan premium.',
    image:
      '/images/categories/fashion-stylish.jpg',
    icon: 'Sparkles',
    productCount: 1,
  },

  {
    slug: 'polo-shirt',
    name: 'Polo Shirt',
    description:
      'Polo shirt premium dengan bordir logo atau sablon untuk seragam kerja dan komunitas.',
    image:
      '/images/categories/polo-shirt.jpg',
    icon: 'Shirt',
    productCount: 10,
  },
  {
    slug: 'wearpack',
    name: 'Wearpack',
    description:
      'Wearpack industri dan lapangan dengan bahan ripstop yang kuat, aman, dan nyaman dipakai.',
    image:
      '/images/categories/wearpack.jpg',
    icon: 'HardHat',
    productCount: 8,
  },
  {
    slug: 'almamater',
    name: 'Almamater & Jaz',
    description:
      'Koleksi almamater dan jaket premium dengan desain eksklusif dan bahan berkualitas tinggi. Cocok untuk wisuda, organisasi, komunitas, dan acara spesial.',
    image:
      '/images/categories/almamater.jpg',
    icon: 'Wind',
    productCount: 7,
  },
  {
    slug: 'bahan-kain',
    name: 'Bahan Kain',
    description:
      'Aneka bahan kain grade A: katun combed, drill, polyester, dan lainnya dengan harga grosir.',
    image:
      '/images/categories/bahan-kain.jpg',
    icon: 'Layers',
    productCount: 20,
  },
  {
    slug: 'atribut-sekolah',
    name: 'Atribut Sekolah',
    description:
      'Dasi, topi, dompet, tali nama, sabuk, dan atribut sekolah lengkap dengan kualitas terjamin.',
    image:
      '/images/categories/atribut-sekolah.jpg',
    icon: 'Star',
    productCount: 18,
  },
];

export const products: Product[] = [
  // ─── SERAGAM SEKOLAH ───────────────────────────────────────────────────────
  {
    slug: 'seragam-sekolah-standar',
    name: 'Seragam Sekolah Standar',
    category: 'seragam-sekolah',
    categoryLabel: 'Seragam Sekolah',
    shortDescription: 'Seragam siswa lengkap dengan bahan adem dan jahitan rapi.',
    description:
      'Seragam sekolah standar dengan bahan katun twill premium yang adem, tidak menerawang, dan tahan lama. Jahitan rantai di area kritikal memastikan ketahanan saat dicuci berulang. Tersedia untuk SD, SMP, dan SMA dengan warna sesuai standar sekolah.',
    images: [
      '/images/products/seragam-sekolah-standar/foto-1.jpg',
      '/images/products/seragam-sekolah-standar/foto-2.jpg',
      '/images/products/seragam-sekolah-standar/foto-3.jpg',
      '/images/products/seragam-sekolah-standar/foto-4.jpg',
    ],
    basePrice: 102500,
    educationPricing: [
      { level: 'SD', basePrice: 105000, label: 'Sekolah Dasar' },
      { level: 'SMP', basePrice: 120000, label: 'Sekolah Menengah Pertama' },
      { level: 'SMA', basePrice: 135000, label: 'Sekolah Menengah Atas' },
    ],
    priceTiers: [
      { minQty: 10, maxQty: 49, discount: 0, label: '10–49 pcs' },
      { minQty: 50, maxQty: 99, discount: 1000, label: '50–99 pcs' },
      { minQty: 100, maxQty: 199, discount: 1500, label: '100–199 pcs' },
      { minQty: 200, maxQty: 500, discount: 2500, label: '200–500 pcs' },
    ],
    colors: [
      { name: 'Putih', hex: '#f8fafc' },
      { name: 'Navy', hex: '#0a0a2e' },
      { name: 'Merah Maroon', hex: '#7f1d1d' },
      { name: 'Abu', hex: '#64748b' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.9,
    reviewCount: 128,
    badge: 'Best Seller',
    features: [
      'Bahan katun twill premium, adem dan tidak menerawang',
      'Jahitan rantai di area kritikal untuk ketahanan ekstra',
      'Tersedia warna sesuai standar sekolah',
      'Bordir nama sekolah gratis (min. 50 pcs)',
      'Quality control ketat sebelum pengiriman',
    ],
    specifications: [
      { label: 'Bahan', value: 'Katun Twill 30s' },
      { label: 'Tebal Kain', value: '180–200 gsm' },
      { label: 'Teknik Bordir', value: 'Computerized Embroidery' },
      { label: 'MOQ', value: '10 pcs' },
      { label: 'Estimasi Produksi', value: '7–10 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://s.shopee.co.id/20tQvxOu1S',
  },
  {
    slug: 'seragam-olahraga-sekolah',
    name: 'Seragam Olahraga Sekolah',
    category: 'seragam-sekolah',
    categoryLabel: 'Seragam Sekolah',
    shortDescription: 'Baju olahraga sekolah bahan drifit breathable, anti keringat.',
    description:
      'Seragam olahraga sekolah dengan bahan drifit polyester yang menyerap keringat cepat, ringan, dan nyaman dipakai aktivitas tinggi. Sablon nama sekolah dan logo dengan teknik heat transfer premium. Tersedia untuk SD, SMP, dan SMA.',
    images: [
      '/images/products/seragam-olahraga-sekolah/foto-1.jpg',
      '/images/products/seragam-olahraga-sekolah/foto-2.jpg',
      '/images/products/seragam-olahraga-sekolah/foto-3.jpg',
      '/images/products/seragam-olahraga-sekolah/foto-4.jpg',
    ],
    basePrice: 58000,
    educationPricing: [
      { level: 'SD', basePrice: 60000, label: 'Sekolah Dasar' },
      { level: 'SMP', basePrice: 70000, label: 'Sekolah Menengah Pertama' },
      { level: 'SMA', basePrice: 80000, label: 'Sekolah Menengah Atas' },
    ],
    priceTiers: [
      { minQty: 10, maxQty: 49, discount: 0, label: '10–49 pcs' },
      { minQty: 50, maxQty: 99, discount: 1000, label: '50–99 pcs' },
      { minQty: 100, maxQty: 199, discount: 1500, label: '100–199 pcs' },
      { minQty: 200, maxQty: 500, discount: 2500, label: '200–500 pcs' },
    ],
    colors: [
      { name: 'Putih', hex: '#f8fafc' },
      { name: 'Navy', hex: '#0a0a2e' },
      { name: 'Merah', hex: '#dc2626' },
      { name: 'Hijau', hex: '#16a34a' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviewCount: 94,
    badge: 'Populer',
    features: [
      'Bahan drifit polyester, menyerap keringat cepat',
      'Ringan dan elastis untuk aktivitas tinggi',
      'Sablon heat transfer tahan lama',
      'Jahitan flatlock yang nyaman di kulit',
      'Quality control ketat sebelum pengiriman',
    ],
    specifications: [
      { label: 'Bahan', value: 'Drifit Polyester' },
      { label: 'Tebal Kain', value: '140–160 gsm' },
      { label: 'Teknik Sablon', value: 'Heat Transfer' },
      { label: 'MOQ', value: '10 pcs' },
      { label: 'Estimasi Produksi', value: '5–7 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://s.shopee.co.id/20tQvxOu1S',
  },
  {
    slug: 'celana-sekolah',
    name: 'Celana Sekolah Standar',
    category: 'seragam-sekolah',
    categoryLabel: 'Seragam Sekolah',
    shortDescription: 'Celana sekolah bahan drill premium dengan ketahanan tinggi.',
    description:
      'Celana sekolah dengan bahan drill yang tidak mudah kusut, tahan lama, dan nyaman dipakai seharian. Jahitan rantai di area kritikal untuk ketahanan ekstra. Tersedia untuk SD, SMP, dan SMA dengan warna sesuai standar sekolah.',
    images: [
      '/images/products/celana-sekolah/foto-1.jpg',
      '/images/products/celana-sekolah/foto-2.jpg',
      '/images/products/celana-sekolah/foto-3.jpg',
      '/images/products/celana-sekolah/foto-4.jpg',
    ],
    basePrice: 75000,
    educationPricing: [
      { level: 'SD', basePrice: 75000, label: 'Sekolah Dasar' },
      { level: 'SMP', basePrice: 85000, label: 'Sekolah Menengah Pertama' },
      { level: 'SMA', basePrice: 95000, label: 'Sekolah Menengah Atas' },
    ],
    priceTiers: [
      { minQty: 10, maxQty: 49, discount: 0, label: '10–49 pcs' },
      { minQty: 50, maxQty: 99, discount: 1000, label: '50–99 pcs' },
      { minQty: 100, maxQty: 199, discount: 1500, label: '100–199 pcs' },
      { minQty: 200, maxQty: 500, discount: 2500, label: '200–500 pcs' },
    ],
    colors: [
      { name: 'Abu', hex: '#64748b' },
      { name: 'Navy', hex: '#0a0a2e' },
      { name: 'Hitam', hex: '#0f172a' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviewCount: 87,
    features: [
      'Bahan drill premium, tidak mudah kusut',
      'Jahitan rantai di area kritikal',
      'Tersedia warna sesuai standar sekolah',
      'Bordir nama sekolah gratis (min. 50 pcs)',
      'Quality control ketat sebelum pengiriman',
    ],
    specifications: [
      { label: 'Bahan', value: 'Drill 200 gsm' },
      { label: 'Model', value: 'Celana Pendek / Panjang' },
      { label: 'MOQ', value: '10 pcs' },
      { label: 'Estimasi Produksi', value: '7–10 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://s.shopee.co.id/20tQvxOu1S',
  },
  {
    slug: 'kaos-kaki-custom',
    name: 'Kaos Kaki Custom',
    category: 'atribut-sekolah',
    categoryLabel: 'Atribut Sekolah',
    shortDescription: 'Kaos kaki custom dengan bahan katun combed breathable dan sablon logo.',
    description:
      'Kaos kaki custom dengan bahan katun combed 30s yang breathable, menyerap keringat, dan nyaman dipakai seharian. Sablon logo atau tulisan dengan teknik screen printing premium yang tidak mudah luntur. Tersedia berbagai ukuran dan warna custom sesuai kebutuhan sekolah atau komunitas.',
    images: [
      '/images/products/kaos-kaki-custom/foto-1.jpg',
      '/images/products/kaos-kaki-custom/foto-2.jpg',
    ],
    basePrice: 15000,
    priceTiers: [
      { minQty: 50, maxQty: 99, discount: 0, label: '50–99 pcs' },
      { minQty: 100, maxQty: 199, discount: 500, label: '100–199 pcs' },
      { minQty: 200, maxQty: 499, discount: 1000, label: '200–499 pcs' },
      { minQty: 500, maxQty: 1000, discount: 1500, label: '500–1000 pcs' },
    ],
    colors: [
      { name: 'Putih', hex: '#f8fafc' },
      { name: 'Hitam', hex: '#0a0a0a' },
      { name: 'Navy', hex: '#0a0a2e' },
      { name: 'Abu', hex: '#64748b' },
      { name: 'Custom', hex: '#d4af37' },
    ],
    sizes: ['S (35-37)', 'M (38-40)', 'L (41-43)', 'XL (44-46)'],
    rating: 4.8,
    reviewCount: 42,
    features: [
      'Bahan katun combed 30s breathable',
      'Menyerap keringat dengan baik',
      'Sablon logo custom tidak mudah luntur',
      'Elastis dan nyaman dipakai',
      'Quality control ketat sebelum pengiriman',
    ],
    specifications: [
      { label: 'Bahan', value: 'Katun Combed 30s' },
      { label: 'Model', value: 'Kaos Kaki Custom' },
      { label: 'MOQ', value: '50 pcs' },
      { label: 'Estimasi Produksi', value: '5–7 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://s.shopee.co.id/20tQvxOu1S',
  },
  {
    slug: 'jas-labschool',
    name: 'Jas Labschool Premium',
    category: 'seragam-sekolah',
    categoryLabel: 'Seragam Sekolah',
    shortDescription: 'Jas lab seragam sekolah dengan bahan yang tahan kimia dan mudah dicuci.',
    description:
      'Jas lab seragam sekolah dengan bahan drill tahan kimia dan mudah dicuci. Model kancing depan, saku fungsional, dan kantong pensil. Cocok untuk praktikum IPA, Biologi, Kimia, dan Fisika. Tersedia untuk SD, SMP, dan SMA.',
    images: [
      '/images/products/jas-labschool/foto-1.jpg',
      '/images/products/jas-labschool/foto-2.jpg',
      '/images/products/jas-labschool/foto-3.jpg',
      '/images/products/jas-labschool/foto-4.jpg',
    ],
    basePrice: 65000,
    educationPricing: [
      { level: 'SD', basePrice: 65000, label: 'Sekolah Dasar' },
      { level: 'SMP', basePrice: 75000, label: 'Sekolah Menengah Pertama' },
      { level: 'SMA', basePrice: 85000, label: 'Sekolah Menengah Atas' },
    ],
    priceTiers: [
      { minQty: 10, maxQty: 49, discount: 0, label: '10–49 pcs' },
      { minQty: 50, maxQty: 99, discount: 1000, label: '50–99 pcs' },
      { minQty: 100, maxQty: 199, discount: 1500, label: '100–199 pcs' },
      { minQty: 200, maxQty: 500, discount: 2500, label: '200–500 pcs' },
    ],
    colors: [
      { name: 'Putih', hex: '#f8fafc' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.7,
    reviewCount: 52,
    features: [
      'Bahan drill tahan kimia dan mudah dicuci',
      'Model kancing depan dengan saku fungsional',
      'Kantong pensil di lengan',
      'Bordir nama sekolah gratis (min. 50 pcs)',
      'Quality control ketat sebelum pengiriman',
    ],
    specifications: [
      { label: 'Bahan', value: 'Drill 180 gsm' },
      { label: 'Model', value: 'Jas Lab / Apron' },
      { label: 'MOQ', value: '10 pcs' },
      { label: 'Estimasi Produksi', value: '7–10 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://s.shopee.co.id/20tQvxOu1S',
  },

  // FASHION STYLISH
  {
    slug: 'rok-sekolah',
    name: 'Rok Plisket Dewasa Premium',
    category: 'fashion-stylish',
    categoryLabel: 'Fashion Stylish',
    shortDescription: 'Rok plisket premium outfit stylish cewek gen z.',
    description:
      'Rok plisket premium dengan bahan berkualitas dan model stylish. Cocok untuk outfit sehari-hari, kuliah, atau acara casual. Tersedia dalam berbagai warna dan ukuran.',
    images: [
      '/images/products/rok-sekolah-plisket/foto-1.jpg',
      '/images/products/rok-sekolah-plisket/foto-2.jpg',
      '/images/products/rok-sekolah-plisket/foto-3.jpg',
      '/images/products/rok-sekolah-plisket/foto-4.jpg',
    ],
    basePrice: 60000,
    priceTiers: [
      { minQty: 10, maxQty: 49, discount: 0, label: '10–49 pcs' },
      { minQty: 50, maxQty: 99, discount: 1000, label: '50–99 pcs' },
      { minQty: 100, maxQty: 199, discount: 1500, label: '100–199 pcs' },
      { minQty: 200, maxQty: 500, discount: 2500, label: '200–500 pcs' },
    ],
    colors: [
      { name: 'Abu', hex: '#64748b' },
      { name: 'Navy', hex: '#0a0a2e' },
      { name: 'Hitam', hex: '#0f172a' },
      { name: 'Putih', hex: '#f8fafc' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviewCount: 72,
    features: [
      'Bahan serge premium, jatuh sempurna',
      'Tidak mudah kusut dan tahan lama',
      'Tersedia model plisket dan polos',
      'Tersedia ukuran anak hingga dewasa',
      'Quality control ketat sebelum pengiriman',
    ],
    specifications: [
      { label: 'Bahan', value: 'Serge Premium' },
      { label: 'Model', value: 'Plisket / Polos' },
      { label: 'MOQ', value: '10 pcs' },
      { label: 'Estimasi Produksi', value: '5–7 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://s.shopee.co.id/20tQvxOu1S',
  },

  // ─── SERAGAM PERUSAHAAN ────────────────────────────────────────────────────
  {
    slug: 'seragam-perusahaan-polo',
    name: 'Seragam Perusahaan Polo',
    category: 'seragam-perusahaan',
    categoryLabel: 'Seragam Perusahaan',
    shortDescription: 'Polo shirt premium dengan bordir logo perusahaan.',
    description:
      'Polo shirt seragam perusahaan dengan bahan lacoste pique yang breathable dan tahan kusut. Bordir logo perusahaan dengan teknik computerized embroidery menghasilkan detail tajam dan tahan lama. Cocok untuk staff, sales, dan event perusahaan.',
    images: [
      '/images/products/seragam-perusahaan-polo/foto-1.jpg',
      '/images/products/seragam-perusahaan-polo/foto-2.jpg',
      '/images/products/seragam-perusahaan-polo/foto-3.jpg',
      '/images/products/seragam-perusahaan-polo/foto-4.jpg',
    ],
    basePrice: 70000,
    priceTiers: [
      { minQty: 10, maxQty: 49, price: 70000, label: '10–49 pcs' },
      { minQty: 50, maxQty: 99, price: 69000, label: '50–99 pcs' },
      { minQty: 100, maxQty: 199, price: 68500, label: '100–199 pcs' },
      { minQty: 200, maxQty: 299, price: 68000, label: '200–299 pcs' },
      { minQty: 300, maxQty: 500, price: 67500, label: '300–500 pcs' },
    ],
    colors: [
      { name: 'Navy', hex: '#0a0a2e' },
      { name: 'Hitam', hex: '#0f172a' },
      { name: 'Putih', hex: '#f8fafc' },
      { name: 'Maroon', hex: '#7f1d1d' },
      { name: 'Forest', hex: '#14532d' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviewCount: 86,
    badge: 'Premium',
    features: [
      'Bahan lacoste pique 30s, breathable dan tahan kusut',
      'Bordir logo computerized dengan detail tajam',
      'Kerah dan manset double needle untuk ketahanan',
      'Tersedia 15+ warna pilihan',
      'Quality control ketat sebelum pengiriman',
    ],
    specifications: [
      { label: 'Bahan', value: 'Lacoste Pique 30s' },
      { label: 'Tebal Kain', value: '200–220 gsm' },
      { label: 'Teknik Logo', value: 'Computerized Embroidery' },
      { label: 'MOQ', value: '10 pcs' },
      { label: 'Estimasi Produksi', value: '7–10 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://s.shopee.co.id/20tQvxOu1S',
  },
  {
    slug: 'kemeja-seragam-perusahaan',
    name: 'Kemeja Seragam Perusahaan',
    category: 'seragam-perusahaan',
    categoryLabel: 'Seragam Perusahaan',
    shortDescription: 'Kemeja seragam formal kantor dengan bordir logo profesional.',
    description:
      'Kemeja seragam perusahaan dengan bahan katun CVC yang tidak mudah kusut dan nyaman dipakai seharian. Model lengan panjang dan pendek tersedia. Bordir logo di dada kiri dengan teknik computerized untuk tampilan profesional.',
    images: [
      '/images/products/kemeja-seragam-perusahaan/foto-1.jpg',
      '/images/products/kemeja-seragam-perusahaan/foto-2.jpg',
      '/images/products/kemeja-seragam-perusahaan/foto-3.jpg',
      '/images/products/kemeja-seragam-perusahaan/foto-4.jpg',
    ],
    basePrice: 120000,
    priceTiers: [
      { minQty: 10, maxQty: 49, price: 120000, label: '10–49 pcs' },
      { minQty: 50, maxQty: 99, price: 119000, label: '50–99 pcs' },
      { minQty: 100, maxQty: 199, price: 118500, label: '100–199 pcs' },
      { minQty: 200, maxQty: 299, price: 118000, label: '200–299 pcs' },
      { minQty: 300, maxQty: 500, price: 117500, label: '300–500 pcs' },
    ],
    priceRange: { min: 117500, max: 135000 },
    colors: [
      { name: 'Putih', hex: '#f8fafc' },
      { name: 'Biru Muda', hex: '#bfdbfe' },
      { name: 'Cream', hex: '#fef9c3' },
      { name: 'Abu Muda', hex: '#e2e8f0' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.7,
    reviewCount: 61,
    badge: 'Populer',
    features: [
      'Bahan katun CVC, tidak mudah kusut',
      'Model lengan panjang & pendek tersedia',
      'Bordir logo dada kiri',
      'Finishing rapi dan profesional',
      'Quality control ketat sebelum pengiriman',
    ],
    specifications: [
      { label: 'Bahan', value: 'Katun CVC 40s' },
      { label: 'Tebal Kain', value: '120–140 gsm' },
      { label: 'Teknik Logo', value: 'Computerized Embroidery' },
      { label: 'MOQ', value: '10 pcs' },
      { label: 'Estimasi Produksi', value: '7–10 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://s.shopee.co.id/20tQvxOu1S',
  },

  // ─── KAOS CUSTOM ──────────────────────────────────────────────────────────
  {
    slug: 'kaos-custom-combed',
    name: 'Kaos Custom Combed 30s',
    category: 'kaos-custom',
    categoryLabel: 'Kaos Custom',
    shortDescription: 'Kaos sablon custom bahan katun combed 30s premium.',
    description:
      'Kaos custom dengan bahan katun combed 30s yang lembut, adem, dan jatuh sempurna. Sablon menggunakan tinta plastisol / waterbased yang aman dan tahan lama. Cocok untuk event, komunitas, merchandise, dan promo.',
    images: [
      '/images/products/kaos-custom-combed/foto-1.jpg',
      '/images/products/kaos-custom-combed/foto-2.jpg',
    ],
    basePrice: 45000,
    priceTiers: [
      { minQty: 10, maxQty: 49, price: 45000, label: '10–49 pcs' },
      { minQty: 50, maxQty: 199, price: 38000, label: '50–199 pcs' },
      { minQty: 200, maxQty: null, price: 32000, label: '200+ pcs' },
    ],
    colors: [
      { name: 'Putih', hex: '#f8fafc' },
      { name: 'Hitam', hex: '#0f172a' },
      { name: 'Navy', hex: '#0a0a2e' },
      { name: 'Maroon', hex: '#7f1d1d' },
      { name: 'Olive', hex: '#3f6212' },
      { name: 'Mustard', hex: '#c9a84c' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.9,
    reviewCount: 215,
    badge: 'Populer',
    features: [
      'Bahan katun combed 30s, lembut dan adem',
      'Sablon plastisol / waterbased tahan lama',
      'Jahitan rantai di bahu dan ketiak',
      'Gratis desain artwork',
      'Quality control sebelum pengiriman',
    ],
    specifications: [
      { label: 'Bahan', value: 'Katun Combed 30s' },
      { label: 'Tebal Kain', value: '180 gsm' },
      { label: 'Teknik Sablon', value: 'Plastisol / Waterbased' },
      { label: 'MOQ', value: '10 pcs' },
      { label: 'Estimasi Produksi', value: '5–7 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://s.shopee.co.id/20tQvxOu1S',
  },
  {
    slug: 'kaos-oversize-custom',
    name: 'Kaos Oversize Custom',
    category: 'kaos-custom',
    categoryLabel: 'Kaos Custom',
    shortDescription: 'Kaos oversize custom bahan cotton bamboo premium untuk streetwear.',
    description:
      'Kaos oversize dengan bahan cotton bamboo yang lembut, adem, dan jatuh bagus untuk tampilan streetwear kekinian. Sablon DTF (Direct To Film) full color dengan detail tinggi. Cocok untuk brand clothing, merchandise komunitas, dan event.',
    images: [
      '/images/products/kaos-oversize-custom/foto-1.jpg',
      '/images/products/kaos-oversize-custom/foto-2.jpg',
      '/images/products/kaos-oversize-custom/foto-3.jpg',
      '/images/products/kaos-oversize-custom/foto-4.jpg',
    ],
    basePrice: 55000,
    priceTiers: [
      { minQty: 10, maxQty: 49, price: 55000, label: '10–49 pcs' },
      { minQty: 50, maxQty: 99, price: 54000, label: '50–99 pcs' },
      { minQty: 100, maxQty: 199, price: 53500, label: '100–199 pcs' },
      { minQty: 200, maxQty: 299, price: 53000, label: '200–299 pcs' },
      { minQty: 300, maxQty: 500, price: 52500, label: '300–500 pcs' },
    ],
    colors: [
      { name: 'Putih', hex: '#f8fafc' },
      { name: 'Hitam', hex: '#0f172a' },
      { name: 'Sand', hex: '#d2b48c' },
      { name: 'Sage', hex: '#7fa98a' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.9,
    reviewCount: 143,
    badge: 'Trending',
    features: [
      'Bahan cotton bamboo, lembut dan adem',
      'Sablon DTF full color detail tinggi',
      'Potongan oversize trendi',
      'Gratis desain artwork',
      'Quality control sebelum pengiriman',
    ],
    specifications: [
      { label: 'Bahan', value: 'Cotton Bamboo' },
      { label: 'Tebal Kain', value: '200 gsm' },
      { label: 'Teknik Sablon', value: 'DTF (Direct To Film)' },
      { label: 'MOQ', value: '10 pcs' },
      { label: 'Estimasi Produksi', value: '5–7 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://s.shopee.co.id/20tQvxOu1S',
  },

  // ─── POLO SHIRT ───────────────────────────────────────────────────────────
  {
    slug: 'polo-shirt-lacoste',
    name: 'Polo Shirt Lacoste Pique',
    category: 'polo-shirt',
    categoryLabel: 'Polo Shirt',
    shortDescription: 'Polo shirt lacoste pique premium dengan bordir logo kustom.',
    description:
      'Polo shirt dengan bahan lacoste pique grade A yang breathable, tahan kusut, dan nyaman dipakai seharian. Bordir logo dengan computerized embroidery menghasilkan detail yang tajam. Cocok untuk seragam kerja, komunitas, dan event.',
    images: [
      '/images/products/polo-shirt-lacoste/foto-1.jpg',
      '/images/products/polo-shirt-lacoste/foto-2.jpg',
      '/images/products/polo-shirt-lacoste/foto-3.jpg',
      '/images/products/polo-shirt-lacoste/foto-4.jpg',
    ],
    basePrice: 80000,
    priceTiers: [
      { minQty: 10, maxQty: 49, price: 80000, label: '10–49 pcs' },
      { minQty: 50, maxQty: 199, price: 70000, label: '50–199 pcs' },
      { minQty: 200, maxQty: null, price: 62000, label: '200+ pcs' },
    ],
    colors: [
      { name: 'Navy', hex: '#0a0a2e' },
      { name: 'Hitam', hex: '#0f172a' },
      { name: 'Putih', hex: '#f8fafc' },
      { name: 'Merah', hex: '#dc2626' },
      { name: 'Abu', hex: '#64748b' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.9,
    reviewCount: 177,
    badge: 'Best Seller',
    features: [
      'Bahan lacoste pique grade A, breathable',
      'Bordir logo computerized detail tajam',
      'Kerah dan manset ribbed berkualitas',
      'Tersedia 20+ pilihan warna',
      'Quality control ketat sebelum pengiriman',
    ],
    specifications: [
      { label: 'Bahan', value: 'Lacoste Pique Grade A' },
      { label: 'Tebal Kain', value: '200–220 gsm' },
      { label: 'Teknik Logo', value: 'Computerized Embroidery' },
      { label: 'MOQ', value: '10 pcs' },
      { label: 'Estimasi Produksi', value: '7–10 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://s.shopee.co.id/20tQvxOu1S',
  },
  {
    slug: 'polo-shirt-drifit',
    name: 'Polo Shirt Drifit Sport',
    category: 'polo-shirt',
    categoryLabel: 'Polo Shirt',
    shortDescription: 'Polo shirt drifit sporty untuk olahraga dan aktivitas lapangan.',
    description:
      'Polo shirt drifit dengan bahan polyester microfiber yang ringan, menyerap keringat, dan cepat kering. Cocok untuk seragam olahraga, kepanitiaan, event outdoor, dan aktivitas lapangan. Tersedia dengan opsi sablon atau bordir.',
    images: [
      '/images/products/polo-shirt-drifit/foto-1.jpg',
      '/images/products/polo-shirt-drifit/foto-2.jpg',
      '/images/products/polo-shirt-drifit/foto-3.jpg',
      '/images/products/polo-shirt-drifit/foto-4.jpg',
    ],
    basePrice: 65000,
    priceTiers: [
      { minQty: 10, maxQty: 49, price: 65000, label: '10–49 pcs' },
      { minQty: 50, maxQty: 199, price: 57000, label: '50–199 pcs' },
      { minQty: 200, maxQty: null, price: 50000, label: '200+ pcs' },
    ],
    colors: [
      { name: 'Hitam', hex: '#0f172a' },
      { name: 'Navy', hex: '#0a0a2e' },
      { name: 'Putih', hex: '#f8fafc' },
      { name: 'Merah', hex: '#dc2626' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.7,
    reviewCount: 88,
    features: [
      'Bahan drifit polyester microfiber',
      'Menyerap keringat dan cepat kering',
      'Cocok untuk aktivitas outdoor',
      'Pilihan sablon atau bordir',
      'Quality control ketat sebelum pengiriman',
    ],
    specifications: [
      { label: 'Bahan', value: 'Polyester Microfiber Drifit' },
      { label: 'Tebal Kain', value: '150–170 gsm' },
      { label: 'Teknik Logo', value: 'Sablon / Bordir' },
      { label: 'MOQ', value: '10 pcs' },
      { label: 'Estimasi Produksi', value: '5–7 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://s.shopee.co.id/20tQvxOu1S',
  },

  // ─── WEARPACK ─────────────────────────────────────────────────────────────
  {
    slug: 'wearpack-industri',
    name: 'Wearpack Industri Ripstop',
    category: 'wearpack',
    categoryLabel: 'Wearpack',
    shortDescription: 'Wearpack industri bahan ripstop kuat dan tahan abrasi untuk kerja lapangan.',
    description:
      'Wearpack industri dengan bahan ripstop yang kuat, tahan abrasi, dan nyaman dipakai di lingkungan kerja berat. Jahitan dobel di area tekanan tinggi. Dilengkapi banyak kantong fungsional. Cocok untuk industri manufaktur, tambang, dan konstruksi.',
    images: [
      '/images/products/wearpack-industri-ripstop/foto-1.jpg',
      '/images/products/wearpack-industri-ripstop/foto-2.jpg',
      '/images/products/wearpack-industri-ripstop/foto-3.jpg',
      '/images/products/wearpack-industri-ripstop/foto-4.jpg',
    ],
    basePrice: 185000,
    priceTiers: [
      { minQty: 10, maxQty: 49, price: 185000, label: '10–49 pcs' },
      { minQty: 50, maxQty: 199, price: 165000, label: '50–199 pcs' },
      { minQty: 200, maxQty: null, price: 148000, label: '200+ pcs' },
    ],
    colors: [
      { name: 'Navy', hex: '#0a0a2e' },
      { name: 'Hitam', hex: '#0f172a' },
      { name: 'Abu Tua', hex: '#334155' },
      { name: 'Jingga', hex: '#ea580c' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviewCount: 52,
    badge: 'Premium',
    features: [
      'Bahan ripstop, kuat dan tahan abrasi',
      'Jahitan dobel di area tekanan tinggi',
      'Multi kantong fungsional',
      'Bordir nama/logo perusahaan',
      'Quality control ketat sebelum pengiriman',
    ],
    specifications: [
      { label: 'Bahan', value: 'Ripstop 240 gsm' },
      { label: 'Jahitan', value: 'Double Stitch' },
      { label: 'Teknik Logo', value: 'Computerized Embroidery' },
      { label: 'MOQ', value: '10 pcs' },
      { label: 'Estimasi Produksi', value: '10–14 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://s.shopee.co.id/20tQvxOu1S',
  },
  {
    slug: 'wearpack-mekanik',
    name: 'Wearpack Mekanik Coverall',
    category: 'wearpack',
    categoryLabel: 'Wearpack',
    shortDescription: 'Coverall mekanik satu bagian dengan bahan canvas berkualitas.',
    description:
      'Wearpack model coverall satu bagian untuk mekanik dan teknisi dengan bahan canvas yang tebal dan tahan lama. Resleting YKK berkualitas, kantong banyak dan fungsional, serta bordir nama teknisi untuk tampilan profesional.',
    images: [
      '/images/products/wearpack-mekanik/foto-1.jpg',
      '/images/products/wearpack-mekanik/foto-2.jpg',
      '/images/products/wearpack-mekanik/foto-3.jpg',
      '/images/products/wearpack-mekanik/foto-4.jpg',
    ],
    basePrice: 210000,
    priceTiers: [
      { minQty: 10, maxQty: 49, price: 210000, label: '10–49 pcs' },
      { minQty: 50, maxQty: 199, price: 190000, label: '50–199 pcs' },
      { minQty: 200, maxQty: null, price: 170000, label: '200+ pcs' },
    ],
    colors: [
      { name: 'Navy', hex: '#0a0a2e' },
      { name: 'Hitam', hex: '#0f172a' },
      { name: 'Abu', hex: '#64748b' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviewCount: 37,
    features: [
      'Bahan canvas tebal dan tahan lama',
      'Model coverall satu bagian',
      'Resleting YKK berkualitas',
      'Kantong banyak dan fungsional',
      'Bordir nama/logo perusahaan',
    ],
    specifications: [
      { label: 'Bahan', value: 'Canvas 280 gsm' },
      { label: 'Model', value: 'Coverall / Satu Bagian' },
      { label: 'Resleting', value: 'YKK' },
      { label: 'MOQ', value: '10 pcs' },
      { label: 'Estimasi Produksi', value: '10–14 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://s.shopee.co.id/20tQvxOu1S',
  },

  // ─── ALMAMATER ────────────────────────────────────────────────────────────
  {
    slug: 'jaket-varsity-premium',
    name: 'Almamater & Jaz',
    category: 'almamater',
    categoryLabel: 'Almamater',
    shortDescription: 'Jaket dan almamater premium dengan kombinasi bahan berkualitas dan bordir elegan.',
    description:
      'Jaket dan almamater premium dengan kombinasi body wool premium dan sleeve kulit sintetis berkualitas tinggi. Lining furing lembut di dalam, kancing khas varsity, dan bordir logo yang elegan. Cocok untuk jaket wisuda, almamater organisasi, komunitas, dan acara spesial. Tersedia dalam berbagai warna dan ukuran dengan opsi custom bordir logo.',
    images: [
      '/images/products/jazz-almamater/foto-1.jpg',
      '/images/products/jazz-almamater/foto-2.jpg',
      '/images/products/jazz-almamater/foto-3.jpg',
      '/images/products/jazz-almamater/foto-4.jpg',
    ],
    basePrice: 175000,
    priceTiers: [
      { minQty: 10, maxQty: 49, price: 175000, label: '10–49 pcs' },
      { minQty: 50, maxQty: 199, price: 155000, label: '50–199 pcs' },
      { minQty: 200, maxQty: null, price: 135000, label: '200+ pcs' },
    ],
    colors: [
      { name: 'Navy', hex: '#0a0a2e' },
      { name: 'Hitam', hex: '#0f172a' },
      { name: 'Maroon', hex: '#7f1d1d' },
      { name: 'Forest', hex: '#14532d' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.9,
    reviewCount: 64,
    badge: 'Premium',
    features: [
      'Body wool premium 280 gsm, hangat dan ringan',
      'Sleeve kulit sintetis PU berkualitas',
      'Lining furing lembut di bagian dalam',
      'Kancing khas varsity logam',
      'Bordir logo computerized',
    ],
    specifications: [
      { label: 'Body', value: 'Wool Premium 280 gsm' },
      { label: 'Sleeve', value: 'Kulit Sintetis PU' },
      { label: 'Lining', value: 'Furing Premium' },
      { label: 'MOQ', value: '10 pcs' },
      { label: 'Estimasi Produksi', value: '10–14 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://s.shopee.co.id/20tQvxOu1S',
  },
  {
    slug: 'jaket-bomber',
    name: 'Jaket Bomber Custom',
    category: 'almamater',
    categoryLabel: 'Almamater',
    shortDescription: 'Jaket bomber custom dengan bahan taslan water repellent premium.',
    description:
      'Jaket bomber custom dengan bahan taslan yang water repellent (tahan air ringan) dan windproof. Lining furing fleece yang hangat. Cocok untuk seragam komunitas, kepanitiaan, event outdoor, dan promo brand.',
    images: [
      '/images/products/jaket-bomber/foto-1.jpg',
      '/images/products/jaket-bomber/foto-2.jpg',
      '/images/products/jaket-bomber/foto-3.jpg',
      '/images/products/jaket-bomber/foto-4.jpg',
    ],
    basePrice: 155000,
    priceTiers: [
      { minQty: 10, maxQty: 49, price: 155000, label: '10–49 pcs' },
      { minQty: 50, maxQty: 199, price: 135000, label: '50–199 pcs' },
      { minQty: 200, maxQty: null, price: 120000, label: '200+ pcs' },
    ],
    colors: [
      { name: 'Hitam', hex: '#0f172a' },
      { name: 'Navy', hex: '#0a0a2e' },
      { name: 'Olive', hex: '#3f6212' },
      { name: 'Abu', hex: '#64748b' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviewCount: 49,
    features: [
      'Bahan taslan water repellent & windproof',
      'Lining furing fleece hangat',
      'Resleting YKK berkualitas',
      'Bordir atau sablon logo',
      'Quality control ketat sebelum pengiriman',
    ],
    specifications: [
      { label: 'Bahan', value: 'Taslan Water Repellent' },
      { label: 'Lining', value: 'Fleece' },
      { label: 'Resleting', value: 'YKK' },
      { label: 'MOQ', value: '10 pcs' },
      { label: 'Estimasi Produksi', value: '10–14 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://s.shopee.co.id/20tQvxOu1S',
  },

  // ─── BAHAN KAIN ───────────────────────────────────────────────────────────
  {
    slug: 'bahan-katun-combed',
    name: 'Bahan Katun Combed 30s',
    category: 'bahan-kain',
    categoryLabel: 'Bahan Kain',
    shortDescription: 'Kain katun combed 30s lembut, adem, dan berkualitas tinggi per meter.',
    description:
      'Kain katun combed 30s grade A yang lembut, adem, dan memiliki tekstur halus. Cocok untuk produksi kaos, baju tidur, dan pakaian casual. Tersedia berbagai warna solid dan motif. Dijual per meter dengan harga grosir.',
    images: [
      '/images/products/bahan-katun-combed/foto-1.jpg',
      '/images/products/bahan-katun-combed/foto-2.jpg',
      '/images/products/bahan-katun-combed/foto-3.jpg',
      '/images/products/bahan-katun-combed/foto-4.jpg',
    ],
    basePrice: 35000,
    priceTiers: [
      { minQty: 10, maxQty: 49, price: 35000, label: '10–49 meter' },
      { minQty: 50, maxQty: 199, price: 30000, label: '50–199 meter' },
      { minQty: 200, maxQty: null, price: 27000, label: '200+ meter' },
    ],
    colors: [
      { name: 'Putih', hex: '#f8fafc' },
      { name: 'Hitam', hex: '#0f172a' },
      { name: 'Navy', hex: '#0a0a2e' },
      { name: 'Maroon', hex: '#7f1d1d' },
    ],
    sizes: ['All Size'],
    rating: 4.9,
    reviewCount: 203,
    badge: 'Best Seller',
    features: [
      'Katun combed 30s grade A',
      'Lembut, adem, tekstur halus',
      'Tersedia 30+ pilihan warna',
      'Bisa request kain per roll',
      'Harga grosir langsung pabrik',
    ],
    specifications: [
      { label: 'Jenis', value: 'Katun Combed 30s' },
      { label: 'Tebal', value: '180 gsm' },
      { label: 'Lebar', value: '150–160 cm' },
      { label: 'Satuan', value: 'Per meter' },
      { label: 'Min. Pembelian', value: '10 meter' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://s.shopee.co.id/20tQvxOu1S',
  },
  {
    slug: 'bahan-serge-drill',
    name: 'Bahan Serge & Drill Seragam',
    category: 'bahan-kain',
    categoryLabel: 'Bahan Kain',
    shortDescription: 'Kain serge dan drill untuk produksi seragam sekolah dan perusahaan.',
    description:
      'Kain serge dan drill berkualitas tinggi yang biasa digunakan untuk produksi seragam sekolah, seragam kantor, dan celana. Bahan tidak mudah kusut, tahan lama, dan memiliki jatuh yang bagus. Dijual per meter.',
    images: [
      '/images/products/bahan-serge-drill/foto-1.jpg',
      '/images/products/bahan-serge-drill/foto-2.jpg',
      '/images/products/bahan-serge-drill/foto-3.jpg',
      '/images/products/bahan-serge-drill/foto-4.jpg',
    ],
    basePrice: 28000,
    priceTiers: [
      { minQty: 10, maxQty: 49, price: 28000, label: '10–49 meter' },
      { minQty: 50, maxQty: 199, price: 24000, label: '50–199 meter' },
      { minQty: 200, maxQty: null, price: 21000, label: '200+ meter' },
    ],
    colors: [
      { name: 'Putih', hex: '#f8fafc' },
      { name: 'Abu', hex: '#64748b' },
      { name: 'Navy', hex: '#0a0a2e' },
      { name: 'Hitam', hex: '#0f172a' },
    ],
    sizes: ['All Size'],
    rating: 4.8,
    reviewCount: 119,
    features: [
      'Serge & drill grade A',
      'Tidak mudah kusut, tahan lama',
      'Jatuh bagus untuk seragam',
      'Tersedia 20+ pilihan warna',
      'Harga grosir langsung pabrik',
    ],
    specifications: [
      { label: 'Jenis', value: 'Serge / Drill' },
      { label: 'Tebal', value: '200–220 gsm' },
      { label: 'Lebar', value: '150 cm' },
      { label: 'Satuan', value: 'Per meter' },
      { label: 'Min. Pembelian', value: '10 meter' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://s.shopee.co.id/20tQvxOu1S',
  },

  // ─── ATRIBUT SEKOLAH ──────────────────────────────────────────────────────
  {
    slug: 'dasi-sekolah',
    name: 'Dasi Sekolah Custom',
    category: 'atribut-sekolah',
    categoryLabel: 'Atribut Sekolah',
    shortDescription: 'Dasi sekolah custom dengan warna dan logo sekolah sesuai permintaan.',
    description:
      'Dasi sekolah custom dengan bahan polyester satin berkualitas, warna dan corak sesuai identitas sekolah. Mudah dipakai dengan klip/karet pengait. Tersedia berbagai model: dasi panjang, kupu-kupu, dan segitiga.',
    images: [
      '/images/products/dasi-sekolah/foto-1.jpg',
      '/images/products/dasi-sekolah/foto-2.jpg',
      '/images/products/dasi-sekolah/foto-3.jpg',
    ],
    basePrice: 12000,
    priceTiers: [
      { minQty: 50, maxQty: 199, price: 12000, label: '50–199 pcs' },
      { minQty: 200, maxQty: 499, price: 10000, label: '200–499 pcs' },
      { minQty: 500, maxQty: null, price: 8500, label: '500+ pcs' },
    ],
    colors: [
      { name: 'Merah-Putih', hex: '#dc2626' },
      { name: 'Biru-Putih', hex: '#2563eb' },
      { name: 'Hijau-Putih', hex: '#16a34a' },
      { name: 'Kustom', hex: '#c9a84c' },
    ],
    sizes: ['All Size'],
    rating: 4.8,
    reviewCount: 156,
    badge: 'Populer',
    features: [
      'Bahan polyester satin berkualitas',
      'Warna dan corak kustom sesuai sekolah',
      'Mudah dipakai dengan klip pengait',
      'Tersedia model panjang, kupu-kupu, segitiga',
      'Tahan lama dan tidak mudah pudar',
    ],
    specifications: [
      { label: 'Bahan', value: 'Polyester Satin' },
      { label: 'Model', value: 'Panjang / Kupu-kupu / Segitiga' },
      { label: 'Pengait', value: 'Klip / Karet' },
      { label: 'MOQ', value: '50 pcs' },
      { label: 'Estimasi Produksi', value: '5–7 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://s.shopee.co.id/20tQvxOu1S',
  },
  {
    slug: 'topi-sekolah',
    name: 'Topi Sekolah Custom',
    category: 'atribut-sekolah',
    categoryLabel: 'Atribut Sekolah',
    shortDescription: 'Topi sekolah custom berbahan drill dengan bordir logo sekolah.',
    description:
      'Topi sekolah custom dengan bahan drill berkualitas yang tidak mudah layu. Bordir logo dan nama sekolah dengan computerized embroidery. Tersedia model topi pet (baseball cap), topi rimba, dan topi dinas sesuai kebutuhan sekolah.',
    images: [
      '/images/products/topi-sekolah-custom/foto-1.jpg',
      '/images/products/topi-sekolah-custom/foto-2.jpg',
      '/images/products/topi-sekolah-custom/foto-3.jpg',
    ],
    basePrice: 18000,
    priceTiers: [
      { minQty: 50, maxQty: 199, price: 18000, label: '50–199 pcs' },
      { minQty: 200, maxQty: 499, price: 15000, label: '200–499 pcs' },
      { minQty: 500, maxQty: null, price: 13000, label: '500+ pcs' },
    ],
    colors: [
      { name: 'Navy', hex: '#0a0a2e' },
      { name: 'Hitam', hex: '#0f172a' },
      { name: 'Abu', hex: '#64748b' },
      { name: 'Putih', hex: '#f8fafc' },
    ],
    sizes: ['All Size'],
    rating: 4.7,
    reviewCount: 98,
    features: [
      'Bahan drill berkualitas, tidak mudah layu',
      'Bordir logo sekolah computerized',
      'Tersedia model pet, rimba, dan dinas',
      'Ukuran adjustable',
      'Quality control ketat sebelum pengiriman',
    ],
    specifications: [
      { label: 'Bahan', value: 'Drill' },
      { label: 'Model', value: 'Pet / Rimba / Dinas' },
      { label: 'Teknik Logo', value: 'Computerized Embroidery' },
      { label: 'MOQ', value: '50 pcs' },
      { label: 'Estimasi Produksi', value: '5–7 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://s.shopee.co.id/20tQvxOu1S',
  },
  {
    slug: 'logo-bordir-komputer',
    name: 'Logo Bordir Komputer Custom',
    category: 'atribut-sekolah',
    categoryLabel: 'Atribut Sekolah',
    shortDescription: 'Jasa bordir komputer profesional untuk logo sekolah, perusahaan, dan komunitas.',
    description:
      'Layanan bordir komputer (computerized embroidery) profesional dengan teknologi high-speed embroidery machine yang presisi. Melayani bordir logo untuk seragam sekolah, kemeja perusahaan, polo shirt, jaket, topi, tas, dan berbagai produk tekstil lainnya. Menggunakan benang polyester berkualitas tinggi yang tahan luntur dan mengkilap. Detail bordir tajam hingga 1cm dengan kerapatan stitch yang sempurna. Gratis konsultasi desain dan setup logo untuk pesanan dalam jumlah tertentu. Cocok untuk sekolah yang ingin membordir logo di seragam, perusahaan untuk merchandise branded, atau komunitas untuk identitas kelompok.',
    images: [
      '/images/products/logo-bordir-komputer/foto-1.jpg',
      '/images/products/logo-bordir-komputer/foto-2.jpg',
      '/images/products/logo-bordir-komputer/foto-3.jpg',
      '/images/products/logo-bordir-komputer/foto-4.jpg',
    ],
    basePrice: 1500,
    priceTiers: [
      { minQty: 50, maxQty: 199, price: 1500, label: '5cm (50–199 pcs)' },
      { minQty: 200, maxQty: 499, price: 3000, label: '10cm (200–499 pcs)' },
      { minQty: 500, maxQty: null, price: 4500, label: '15cm (500+ pcs)' },
    ],
    priceRange: { min: 1500, max: 4500 },
    colors: [
      { name: 'Full Color', hex: '#000000' },
      { name: 'Custom', hex: '#64748b' },
    ],
    sizes: ['All Size'],
    rating: 4.9,
    reviewCount: 256,
    badge: 'Best Seller',
    features: [
      'Computerized embroidery machine high-speed',
      'Benang polyester premium, tahan luntur',
      'Detail bordir tajam hingga 1cm',
      'Gratis setup logo untuk pesanan tertentu',
      'Bisa bordir di berbagai media (kain, kulit, tas)',
      'Quality control ketat setiap hasil bordir',
    ],
    specifications: [
      { label: 'Teknologi', value: 'Computerized Embroidery (12-15 heads)' },
      { label: 'Jenis Benang', value: 'Polyester 120D/2' },
      { label: 'Ukuran Maksimum', value: '30cm x 40cm' },
      { label: 'Minimum Order', value: '50 pcs' },
      { label: 'Estimasi Produksi', value: '5–10 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://s.shopee.co.id/20tQvxOu1S',
  },
  {
    slug: 'tali-nama-sekolah',
    name: 'Tali Nama / ID Card Holder Sekolah',
    category: 'atribut-sekolah',
    categoryLabel: 'Atribut Sekolah',
    shortDescription: 'Tali nama dan ID card holder custom dengan logo dan nama sekolah.',
    description:
      'Tali nama dan ID card holder custom dengan bahan polyester berkualitas. Sablon atau bordir logo dan nama sekolah. Model tali leher dengan klip kancing atau velcro. Tersedia berbagai warna dan ukuran kartu ID.',
    images: [
      '/images/products/tali-nama-sekolah/foto-1.jpg',
      '/images/products/tali-nama-sekolah/foto-2.jpg',
      '/images/products/tali-nama-sekolah/foto-3.jpg',
      '/images/products/tali-nama-sekolah/foto-4.jpg',
    ],
    basePrice: 5000,
    priceTiers: [
      { minQty: 100, maxQty: 299, price: 5000, label: '100–299 pcs' },
      { minQty: 300, maxQty: 499, price: 4000, label: '300–499 pcs' },
      { minQty: 500, maxQty: null, price: 3500, label: '500+ pcs' },
    ],
    colors: [
      { name: 'Biru', hex: '#2563eb' },
      { name: 'Merah', hex: '#dc2626' },
      { name: 'Hijau', hex: '#16a34a' },
      { name: 'Hitam', hex: '#0f172a' },
    ],
    sizes: ['All Size'],
    rating: 4.6,
    reviewCount: 112,
    features: [
      'Bahan polyester berkualitas, tahan lama',
      'Sablon atau bordir logo sekolah',
      'Klip kancing / velcro mudah pasang',
      'Ukuran kartu ID standar',
      'Quality control ketat sebelum pengiriman',
    ],
    specifications: [
      { label: 'Bahan', value: 'Polyester Ribbon' },
      { label: 'Model', value: 'Tali Leher + ID Card Holder' },
      { label: 'Teknik Logo', value: 'Sablon / Bordir' },
      { label: 'MOQ', value: '100 pcs' },
      { label: 'Estimasi Produksi', value: '3–5 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://s.shopee.co.id/20tQvxOu1S',
  },
  {
    slug: 'sabuk-sekolah',
    name: 'Sabuk Sekolah Kulit Sintetis',
    category: 'atribut-sekolah',
    categoryLabel: 'Atribut Sekolah',
    shortDescription: 'Sabuk sekolah dengan bahan kulit sintetis berkualitas dan gesper metal.',
    description:
      'Sabuk sekolah dengan bahan kulit sintetis (PU leather) berkualitas yang tahan lama. Gesper metal chrome atau gold yang kokoh. Lebar standar 3.5 cm untuk anak-anak. Tersedia warna hitam dan coklat dengan berbagai ukuran.',
    images: [
      '/images/products/sabuk-sekolah/foto-1.jpg',
      '/images/products/sabuk-sekolah/foto-2.jpg',
      '/images/products/sabuk-sekolah/foto-3.jpg',
      '/images/products/sabuk-sekolah/foto-4.jpg',
    ],
    basePrice: 18000,
    priceTiers: [
      { minQty: 50, maxQty: 199, price: 18000, label: '50–199 pcs' },
      { minQty: 200, maxQty: 499, price: 15000, label: '200–499 pcs' },
      { minQty: 500, maxQty: null, price: 12500, label: '500+ pcs' },
    ],
    colors: [
      { name: 'Hitam', hex: '#0f172a' },
      { name: 'Coklat', hex: '#92400e' },
    ],
    sizes: ['S', 'M', 'L'],
    rating: 4.7,
    reviewCount: 65,
    features: [
      'Bahan kulit sintetis PU berkualitas',
      'Gesper metal chrome/gold kokoh',
      'Lebar standar 3.5 cm untuk anak',
      'Tersedia berbagai ukuran',
      'Quality control ketat sebelum pengiriman',
    ],
    specifications: [
      { label: 'Bahan', value: 'PU Leather' },
      { label: 'Gesper', value: 'Metal Chrome / Gold' },
      { label: 'Lebar', value: '3.5 cm' },
      { label: 'MOQ', value: '50 pcs' },
      { label: 'Estimasi Produksi', value: '5–7 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://s.shopee.co.id/20tQvxOu1S',
  },
  {
    slug: 'jilbab-sekolah',
    name: 'Jilbab / Hijab Sekolah',
    category: 'atribut-sekolah',
    categoryLabel: 'Atribut Sekolah',
    shortDescription: 'Jilbab sekolah bahan voal/mawar syar\'i dengan bordir nama sekolah.',
    description:
      'Jilbab sekolah dengan bahan voal/mawar yang ringan, adem, dan tidak menerawang. Model syar\'i dengan panjang hingga perut. Bordir nama dan logo sekolah di bagian luar. Tersedia berbagai warna sesuai standar seragam sekolah.',
    images: [
      '/images/products/jilbab-sekolah/foto-1.jpg',
      '/images/products/jilbab-sekolah/foto-2.jpg',
      '/images/products/jilbab-sekolah/foto-3.jpg',
      '/images/products/jilbab-sekolah/foto-4.jpg',
    ],
    basePrice: 35000,
    educationPricing: [
      { level: 'SD', basePrice: 35000, label: 'Sekolah Dasar' },
      { level: 'SMP', basePrice: 40000, label: 'Sekolah Menengah Pertama' },
      { level: 'SMA', basePrice: 45000, label: 'Sekolah Menengah Atas' },
    ],
    priceTiers: [
      { minQty: 50, maxQty: 199, price: 35000, label: '50–199 pcs' },
      { minQty: 200, maxQty: 499, price: 30000, label: '200–499 pcs' },
      { minQty: 500, maxQty: null, price: 27000, label: '500+ pcs' },
    ],
    colors: [
      { name: 'Putih', hex: '#f8fafc' },
      { name: 'Navy', hex: '#0a0a2e' },
      { name: 'Abu', hex: '#64748b' },
      { name: 'Abu Muda', hex: '#e2e8f0' },
    ],
    sizes: ['All Size'],
    rating: 4.8,
    reviewCount: 89,
    badge: 'Populer',
    features: [
      'Bahan voal/mawar ringan, adem, tidak menerawang',
      'Model syar\'i panjang hingga perut',
      'Bordir nama dan logo sekolah',
      'Tersedia berbagai warna seragam',
      'Quality control ketat sebelum pengiriman',
    ],
    specifications: [
      { label: 'Bahan', value: 'Voal / Mawar' },
      { label: 'Model', value: 'Syar\'i / Segi Empat' },
      { label: 'Teknik Logo', value: 'Bordir Computerized' },
      { label: 'MOQ', value: '50 pcs' },
      { label: 'Estimasi Produksi', value: '5–7 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://s.shopee.co.id/20tQvxOu1S',
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter((p) => p.category === categorySlug);
}
